[tool.mypy]
plugins = ["pydantic.mypy", "sqlalchemy.ext.mypy.plugin"]
ignore_missing_imports = true
explicit_package_bases = true

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "I", "W"]
ignore = ["E501"]
